# Generated by Django 2.0.6 on 2018-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_embeddedtweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedtweet',
            name='embed_code',
            field=models.CharField(max_length=20000),
        ),
    ]
