# Generated by Django 2.0.6 on 2018-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180620_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorthand', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=250)),
                ('mkt_cap', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('circ_supply', models.IntegerField(default=0)),
                ('vol_24h_in_usd', models.DecimalField(decimal_places=6, max_digits=20)),
                ('pct_1h', models.DecimalField(decimal_places=6, max_digits=15)),
                ('pct_24h', models.DecimalField(decimal_places=6, max_digits=15)),
                ('pct_7d', models.DecimalField(decimal_places=6, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
