# Generated by Django 2.0.6 on 2018-06-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pricingdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingdata',
            name='circ_supply',
            field=models.BigIntegerField(default=0),
        ),
    ]
