# Generated by Django 2.0.6 on 2018-07-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='facebook',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='investor',
            name='linkedin',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='investor',
            name='twitter',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='investor',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
