# Generated by Django 2.0.6 on 2018-07-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180701_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='investor',
            name='university',
            field=models.CharField(default='', max_length=250),
        ),
    ]
