# Generated by Django 2.0.6 on 2018-06-13 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=200)),
                ('btc_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eth_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xrp_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xlm_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
